/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ReactcallIndexImport } from './routes/reactcall/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as SantaChatIndexImport } from './routes/santa/chat/index'
import { Route as ChildChatRoomIndexImport } from './routes/child-chat/$room/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ReactcallIndexRoute = ReactcallIndexImport.update({
  id: '/reactcall/',
  path: '/reactcall/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const SantaChatIndexRoute = SantaChatIndexImport.update({
  id: '/santa/chat/',
  path: '/santa/chat/',
  getParentRoute: () => rootRoute,
} as any)

const ChildChatRoomIndexRoute = ChildChatRoomIndexImport.update({
  id: '/child-chat/$room/',
  path: '/child-chat/$room/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/reactcall/': {
      id: '/reactcall/'
      path: '/reactcall'
      fullPath: '/reactcall'
      preLoaderRoute: typeof ReactcallIndexImport
      parentRoute: typeof rootRoute
    }
    '/child-chat/$room/': {
      id: '/child-chat/$room/'
      path: '/child-chat/$room'
      fullPath: '/child-chat/$room'
      preLoaderRoute: typeof ChildChatRoomIndexImport
      parentRoute: typeof rootRoute
    }
    '/santa/chat/': {
      id: '/santa/chat/'
      path: '/santa/chat'
      fullPath: '/santa/chat'
      preLoaderRoute: typeof SantaChatIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/home': typeof HomeIndexRoute
  '/reactcall': typeof ReactcallIndexRoute
  '/child-chat/$room': typeof ChildChatRoomIndexRoute
  '/santa/chat': typeof SantaChatIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/home': typeof HomeIndexRoute
  '/reactcall': typeof ReactcallIndexRoute
  '/child-chat/$room': typeof ChildChatRoomIndexRoute
  '/santa/chat': typeof SantaChatIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/': typeof AuthIndexRoute
  '/home/': typeof HomeIndexRoute
  '/reactcall/': typeof ReactcallIndexRoute
  '/child-chat/$room/': typeof ChildChatRoomIndexRoute
  '/santa/chat/': typeof SantaChatIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/reactcall'
    | '/child-chat/$room'
    | '/santa/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/reactcall'
    | '/child-chat/$room'
    | '/santa/chat'
  id:
    | '__root__'
    | '/'
    | '/auth/'
    | '/home/'
    | '/reactcall/'
    | '/child-chat/$room/'
    | '/santa/chat/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ReactcallIndexRoute: typeof ReactcallIndexRoute
  ChildChatRoomIndexRoute: typeof ChildChatRoomIndexRoute
  SantaChatIndexRoute: typeof SantaChatIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  ReactcallIndexRoute: ReactcallIndexRoute,
  ChildChatRoomIndexRoute: ChildChatRoomIndexRoute,
  SantaChatIndexRoute: SantaChatIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/",
        "/home/",
        "/reactcall/",
        "/child-chat/$room/",
        "/santa/chat/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/reactcall/": {
      "filePath": "reactcall/index.tsx"
    },
    "/child-chat/$room/": {
      "filePath": "child-chat/$room/index.tsx"
    },
    "/santa/chat/": {
      "filePath": "santa/chat/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
